name: Dev Status
on:
  push:
    branches: ["main"]
  workflow_dispatch: {}
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Update STATUS.md
        run: |
          mkdir -p dev
          { echo "# Dev Status"; echo; echo "## Last commit"; git log -1 --pretty=format:"- %h %s (%an, %ar)"; echo; \
            echo "## CI & Tests"; echo "[OK] npm ci"; echo "[FAIL] npm test"; echo; \
            echo "## Changed files (last commit)"; git diff-tree --no-commit-id --name-only -r HEAD || true; echo; \
            echo "---"; echo "Notes:"; echo "- ..."; } > dev/STATUS.md

      - id: cpr
        name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          title: "chore(dev): auto-update STATUS.md"
          commit-message: "chore(dev): auto-update STATUS.md [skip ci]"
          branch: ci/dev-status-bot
          delete-branch: true
          add-paths: dev/STATUS.md

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
