name: Dev Status
on:
  push:
    branches: ["main"]
  workflow_dispatch: {}
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Install & Test
        run: |
          if [ -f package.json ]; then
            npm ci || echo install_failed > install.flag
            npm test || echo tests_failed > tests.flag
          fi

      - name: Update STATUS.md
        run: |
          mkdir -p dev
          {
            echo "# Dev Status"
            echo
            echo "## Dernier commit"
            git log -1 --pretty=format:"- %h %s (%an, %ar)"
            echo
            echo "## CI & Tests"
            [ -f install.flag ] && echo "- ❌ npm ci a échoué" || echo "- ✅ npm ci OK"
            [ -f tests.flag ]  && echo "- ❌ npm test a échoué" || echo "- ✅ npm test OK (ou non défini)"
            echo
            echo "## Fichiers modifiés (dernier commit)"
            git diff-tree --no-commit-id --name-only -r HEAD
            echo
            echo "---"
            echo "Notes rapides :"
            echo "- ..."
          } > dev/STATUS.md

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          title: "chore(dev): auto-update STATUS.md"
          commit-message: "chore(dev): auto-update STATUS.md [skip ci]"
          branch: ci/dev-status-bot
          delete-branch: true
          add-paths: dev/STATUS.md
